packages:
  - apps/*
  - packages/*

catalog:
  '@testing-library/jest-dom': ^6.9.1
  '@testing-library/react': ^16.3.2
  '@types/react': ^19.2.14
  '@vitest/coverage-v8': ^4.1.2
  tsup: ^8.5.1
  typescript: ^6.0.2
  vitest: ^4.1.2
